const ACTIONS = {
  FETCH_PERFORMANCE_DATA: 'FETCH_PERFORMANCE_DATA',
  FILTER_PERFORMANCE_DATA: 'FILTER_PERFORMANCE_DATA',
};

const MUTATIONS = {
  SET_PERFORMANCE_DATASET: 'SET_PERFORMANCE_DATASET',
  SET_FILTERED_PERFORMANCE_DATASET: 'SET_FILTERED_PERFORMANCE_DATASET',
};

const GETTERS = {
  GET_PERFORMANCE_DATASET: 'GET_PERFORMANCE_DATASET',
  GET_ORIGINAL_PERFORMANCE_DATASET: 'GET_ORIGINAL_PERFORMANCE_DATASET',
};

export { ACTIONS, MUTATIONS, GETTERS };
